apiVersion: v1
kind: ReplicationController
metadata:
  name: applug 
spec:
  replicas: 1
  template:
     metadata:
        labels:
          role: applug 
     spec:
        containers:
        - name: webplug
          image: kdetony/plugapp:0.1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
