apiVersion: v1
kind: Service
metadata:
   name: lb-applug
spec:
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 8080
       targetPort: 8080
       name: http
   selector:
     role: applug
